name: hcc-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyterlab
  - notebook
  - ipywidgets
  - pip
  - pip:
    - tqdm
    - nbconvert